### ISSUE TITLE
error: method does not override or impleme nt a method from a supertype

### ISSUE THREAD

**Issue by kamiloc** [davidstoneham/react-native-mssql#1]
I installed the package and add the  lines described in README, but, when i try to run: `react-native run-android`, i'm getting this error:

```
... \react-native-mssql\android\src\main\java\com\stonem\mssql\MSSQLPackage.java:28:
error: method does not override or implement a method from a supertype
```

**Comment by davidstoneham** [comment]
This is an issue using react native >45. Not a big one I'll have it fixed up soon

**Comment by kamiloc** [comment]
Do you know if [this package](https://github.com/patriksimek/node-mssql) works on react-native ?

**Comment by davidstoneham** [comment]
This bug is now fixed. This package is created to work with react-native it won't work with react (web) or any other frameworks. Only android is supported at this stage
