### ISSUE TITLE
How to use variable in query 

### ISSUE THREAD

**Issue by ZainabShakeel** [davidstoneham/react-native-mssql#14]
var date;
Select time from table_name where tble_time='date';
How i use any var or state to select the specific data with user input

**Comment by davidstoneham** [comment]
This could be achieved in your JSX code, for example

```
var date = new Date();
const query = `SELECT TOP * FROM USERS WHERE tbl_time = ${date.toISOString()}`
MSSQL.executeQuery(query);
```

**Comment by mtahir08** [comment]
@davidstoneham how can I use mssql procedure functions? like weekStart()

**Comment by davidstoneham** [comment]
@mtahir08 your question is unrelated to this open issue
