### ISSUE TITLE
 Network error IOException

### ISSUE THREAD

**Issue by ghost** [davidstoneham/react-native-mssql#2]
`MSSQL.connect(config)
      .then(result => console.log(result))
      .catch(error => console.warn(error));
`

<img width="861" alt="dingtalk20171122114733" src="https://user-images.githubusercontent.com/6070885/33109151-f9af1b1c-cf7a-11e7-970f-9095abe2fa21.png">

**Comment by davidstoneham** [comment]
Can you post your config json so i can make sure it is formatted correctly? Feel free to hide the username/password characters

**Comment by ghost** [comment]
@davidstoneham 

![dingtalk20171122135928](https://user-images.githubusercontent.com/6070885/33112279-60b2045c-cf8d-11e7-8955-209be72ff230.png)

**Comment by davidstoneham** [comment]
@zhanyulong apologies for the super late reply. This error looks related to either an inability for the device to see the database on the network (are the ports open/no firewalls) or the version of SQL is not compatible with the net.sourceforge.jtds.jdbc.Driver. Can you confirm the database is accessible from another device and your version of MSSQL is [compatible](http://jtds.sourceforge.net/)

**Comment by davidstoneham** [comment]
Closing due to activity and suspect this is related to the database setup and not an issue with the plugin
