### ISSUE TITLE
Does it not work in IOS?

### ISSUE THREAD

**Issue by matheus-kirchesch-old** [davidstoneham/react-native-mssql#20]
If not, are there plans for making it work? or is there some kind of limitation

**Comment by davidstoneham** [comment]
There is currently no iOS support. There isn't a limitation but there are no plans to integrate it

**Comment by RobsonRojas** [comment]
> If not, are there plans for making it work? or is there some kind of limitation

Have you found a solution to ios?

**Comment by davidstoneham** [comment]
iOS support is possible but i have no plans to implement that feature.
