### ISSUE TITLE
 Connection problem to local database

### ISSUE THREAD

**Issue by frtlec** [davidstoneham/react-native-mssql#21]
Do you have a solution for this problem? please help me
Connection problem to local database

Console error:
![image](https://user-images.githubusercontent.com/30453059/90486439-9bb9f280-e141-11ea-874f-82972104c076.png)
My Code
```
`    const config = {
        server: 'localhost\SQLEXPRESS', //ip address of the mssql database
        username: 'zaferkrk2', //username to login to the database
        password: '1234', //password to login to the database
        database: 'Northwind', //the name of the database to connect to
      }
      MSSQL.connect(config);
      const query = 'SELECT TOP * FROM Roles'
      MSSQL.executeQuery(query);
  
      MSSQL.close();`
```

sample connection string (for c#)
**Data Source=localhost\SQLEXPRESS;User ID=zaferkrk2;Password=1234;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False**

**Comment by ahmet021** [comment]
Merhaba mssql bağlantısını yapabildiniz mi ? bir süredir bununla uğraşıyorum fakat  hala ilerleyebilmiş değilim.

**Comment by davidstoneham** [comment]
The plugin is asynchronous so you need to wait for the connection to be established before attempting a query or closing the connection. Please check the readme but as solutoin for the above is
```
const config = {
        server: 'localhost\SQLEXPRESS', //ip address of the mssql database
        username: 'zaferkrk2', //username to login to the database
        password: '1234', //password to login to the database
        database: 'Northwind', //the name of the database to connect to
      }
      await MSSQL.connect(config);
      const query = 'SELECT TOP * FROM Roles'
      const result = await MSSQL.executeQuery(query);
  
      await MSSQL.close();`
```
