### ISSUE TITLE
react-native-mssql

### ISSUE THREAD

**Issue by SaeedArshinchiBonab** [davidstoneham/react-native-mssql#7]
When I want to get a query, I encounter the following.
http://uupload.ir/files/9lau_6.png

**Comment by davidstoneham** [comment]
The connect function is asynchronous so you will need to wait for it to complete successfully before running a query.

e.g.
```
MSSQL.connect(config).then(() => {
    MSSQL.executeQuery(query)
}, err => { 
// error
};
```
or with async
```
try{
    await MSSQL.connect(config);
    MSSQL.executeQuery(query)
catch(ex) {
// error
}
```

**Comment by Walter-Mata** [comment]
any update?

**Comment by WalterBernard** [comment]
![image](https://user-images.githubusercontent.com/29629442/53698256-0c1d6880-3e15-11e9-830b-535551ceffa6.png)

can help me what is my problem on my codes, why does it not work ?

**Comment by Walter-Mata** [comment]
![image](https://user-images.githubusercontent.com/29629442/53698321-0a07d980-3e16-11e9-812e-f2b5e42c1c99.png)

can help me what is my problem in my codes, why does it not work ?

**Comment by davidstoneham** [comment]
Your issue is your emulator cannot access the database IP address or port. You'll need to make sure you can connect to the database from another computer on your local network. 

The connect function is also asynchronous so you'll need to make sure you wait for that to finish before calling any query in the database

**Comment by Walter-Mata** [comment]
![image](https://user-images.githubusercontent.com/29629442/53723384-a37ccd00-3ea2-11e9-9ded-32068ff151c3.png)

stuck on this issue for about 4 hours. i still can't fix the issue. can help me this one?
